export enum WorkflowStep {
  EXTRACTION = 'EXTRACTION',

  EXTRACTION_REVIEW = 'EXTRACTION_REVIEW',

  CLASSIFICATION_REVIEW = 'CLASSIFICATION_REVIEW',

  ACCOUNT_MAPPING_REVIEW = 'ACCOUNT_MAPPING_REVIEW',

  JOURNAL_REVIEW = 'JOURNAL_REVIEW',

  PAYMENT_REVIEW = 'PAYMENT_REVIEW',

  COMPLETED = 'COMPLETED',
}
