import { StateType } from '../state/graph-state';
import { LLM_MODELS } from '../config/llm.config';
import Groq from 'groq-sdk';

/**
 * Report Generation Agent
 *
 * Transforms the Financial Reasoning Agent's structured reasoning output into
 * a professional Markdown report.
 *
 * Can only be invoked by the Financial Reasoning Agent (never directly by the
 * Orchestrator).
 *
 * Supported report types (inferred automatically):
 *  - Financial Analysis Report
 *  - Cost Optimization Report
 *  - Cash Flow Analysis Report
 *  - Budget Planning Report
 *  - Executive Summary
 *  - Quarterly Review Report
 *  - Risk Assessment Report
 *
 * Report structure:
 *  1. Executive Summary
 *  2. Key Findings
 *  3. KPI Analysis
 *  4. Risks
 *  5. Opportunities
 *  6. Recommendations
 *  7. Supporting Evidence
 */
export async function reportGenerationAgentNode(
  state: StateType,
  groqClient: Groq,
): Promise<Partial<StateType>> {
  const { orgSlug, reasoningOutput, userQuery, reportType } = state;

  if (!reasoningOutput) {
    console.warn('Report Generation Agent: no reasoningOutput in state — skipping');
    return {
      reportMarkdown: '',
      agentOutput: 'No reasoning output available to generate a report.',
    };
  }

  console.log('Report Generation Agent: generating report for org:', orgSlug);

  const resolvedReportType = reportType ?? inferReportType(userQuery ?? '');

  const REPORT_SYSTEM_PROMPT = `You are a senior financial report writer for ${orgSlug}.

You have received a structured financial analysis. Your task is to transform it into a professional, readable Markdown report titled: "${resolvedReportType}".

Report structure (use exactly these section headers):

# ${resolvedReportType}
**Organization:** ${orgSlug}
**Generated:** ${new Date().toISOString().split('T')[0]}
**Report Type:** ${resolvedReportType}

---

## 1. Executive Summary
A concise 2-4 sentence narrative of the overall financial health and key conclusions.

## 2. Key Findings
Bullet-point list of the most important facts discovered. Each finding must cite the source data.

## 3. KPI Analysis
| KPI | Value | Trend | Status |
Present key performance indicators in a table. Use ↑ for positive trend, ↓ for negative, → for stable.

## 4. Risks
For each risk: **[Severity: HIGH/MEDIUM/LOW]** — Risk description and evidence.

## 5. Opportunities
Specific, actionable opportunities identified from the financial data.

## 6. Recommendations
Prioritized action items:
- **[PRIORITY: HIGH]** — Action to take, why, expected impact
- **[PRIORITY: MEDIUM]** — ...
- **[PRIORITY: LOW]** — ...

## 7. Supporting Evidence
Key data points and quotes from the financial context that back your findings.

---
*This report was generated by Hesbetak.AI Financial Assistant. All data sourced from verified financial records.*

RULES:
- Use only data present in the analysis input.
- Do not invent numbers, figures, or recommendations.
- Use professional financial language.
- Keep the report concise but complete.
- Use Markdown formatting throughout.`;

  try {
    const response = await groqClient.chat.completions.create({
      model: LLM_MODELS.REPORT_GENERATION_AGENT, // llama-3.3-70b-versatile
      messages: [
        { role: 'system', content: REPORT_SYSTEM_PROMPT },
        {
          role: 'user',
          content: `Please generate the ${resolvedReportType} based on the following analysis:\n\n${reasoningOutput}`,
        },
      ],
      max_tokens: 3000,
      temperature: 0.2,
    });

    const reportMarkdown = response.choices[0]?.message?.content?.trim() ?? '';

    console.log('Report Generation Agent: report generated, length:', reportMarkdown.length);

    // Provide a brief agentOutput summary for the chatting agent to reference
    const agentOutput = reportMarkdown
      ? `A ${resolvedReportType} has been generated for ${orgSlug}. The report covers key findings, KPI analysis, identified risks, opportunities, and prioritized recommendations.`
      : 'Report generation encountered an issue. Please try again.';

    return {
      reportMarkdown,
      agentOutput,
    };
  } catch (error) {
    console.error('Report Generation Agent error:', error);
    return {
      reportMarkdown: '',
      agentOutput: 'Report generation encountered an error. The financial analysis is available in the response.',
    };
  }
}

/**
 * Infers the report title/type from the user's query.
 */
function inferReportType(query: string): string {
  const q = query.toLowerCase();
  if (q.includes('cost') || q.includes('optim')) return 'Cost Optimization Report';
  if (q.includes('cash') || q.includes('liquidity')) return 'Cash Flow Analysis Report';
  if (q.includes('risk') || q.includes('exposure')) return 'Risk Assessment Report';
  if (q.includes('profit') || q.includes('margin')) return 'Profitability Analysis Report';
  if (q.includes('budget') || q.includes('plan')) return 'Budget Planning Report';
  if (q.includes('forecast')) return "forecasting report"
  if (q.includes('executive') || q.includes('overview')) return 'Executive Summary';
  if (q.includes('quarter') || q.includes('quarterly')) return 'Quarterly Review Report';
  return 'Financial Analysis Report';
}
